services:
  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./react
    ports:
      - "5173:80" 
    depends_on:
      - backend

  backend:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo-data:
